import { useEffect, useState } from 'react'
import { FileCode2, GitCommitHorizontal, Loader2, ShieldCheck } from 'lucide-react'
import * as api from '@/api/client'

type Props = { context: { workbenchId: string; worktreeId: string }; selection: any; hidden?: boolean }

export default function VersionControlDetailsDock({ context, selection, hidden }: Props) {
  const [diff, setDiff] = useState<api.VcDiffResult | null>(null)
  const [loading, setLoading] = useState(false)
  const entry = selection?.entry ?? selection?.difference
  const filePath = entry?.filePath ?? entry?.relativePath
  useEffect(() => { if (!filePath) { setDiff(null); return } let cancelled = false; setLoading(true); api.getWorktreeVcDiff(context.workbenchId, context.worktreeId, filePath).then(value => { if (!cancelled) setDiff(value) }).catch(() => { if (!cancelled) setDiff(null) }).finally(() => { if (!cancelled) setLoading(false) }); return () => { cancelled = true } }, [context.workbenchId, context.worktreeId, filePath])
  if (hidden) return null
  if (!selection) return <aside className="flex h-full w-full items-center justify-center p-4 text-center text-[9px] text-muted-foreground">Select a PLC object, commit, or validation record to inspect its details.</aside>
  if (selection.kind === 'commit') return <aside className="flex h-full w-full flex-col gap-3 overflow-y-auto p-3" aria-label="Version control details"><div className="flex items-center gap-2 text-[10px] font-semibold"><GitCommitHorizontal className="h-3.5 w-3.5 text-chart-3" />Commit {selection.commit.sha.slice(0, 8)}</div><div className="text-[9px]">{selection.commit.message}</div><div className="text-[8px] text-muted-foreground">{selection.commit.author} · {selection.commit.timestamp}</div><div className="space-y-1"><div className="text-[8px] uppercase text-muted-foreground">Changed PLC objects</div>{selection.commit.files.map((path: string) => <div key={path} className="font-mono text-[8px]">{path}</div>)}</div></aside>
  return <aside className="flex h-full w-full flex-col gap-3 overflow-y-auto p-3" aria-label="Version control details"><div className="flex items-center gap-2 text-[10px] font-semibold"><FileCode2 className="h-3.5 w-3.5 text-chart-2" />{entry.objectName ?? entry.identity ?? 'PLC source object'}</div><div className="space-y-1 text-[8px]"><div><span className="text-muted-foreground">PLC:</span> {entry.plcName ?? entry.deviceId}</div><div><span className="text-muted-foreground">Category:</span> {entry.category ?? 'Program block'}</div><div className="font-mono"><span className="text-muted-foreground">Path:</span> {filePath}</div><div><span className="text-muted-foreground">State:</span> {entry.state ?? entry.kind}</div>{entry.masterFingerprint && <div className="font-mono"><span className="text-muted-foreground">Master fingerprint:</span> {entry.masterFingerprint}</div>}{entry.tiaFingerprint && <div className="font-mono"><span className="text-muted-foreground">TIA fingerprint:</span> {entry.tiaFingerprint}</div>}</div><div className="flex items-center gap-1 text-[9px] font-medium"><ShieldCheck className="h-3 w-3 text-chart-2" />Normalized XML diff</div>{loading ? <Loader2 className="h-3 w-3 animate-spin" /> : diff ? <div className="space-y-1 font-mono text-[8px]">{diff.hunks.flatMap(hunk => hunk.lines).map((line, index) => <div key={index} className={line.type === 'addition' ? 'text-emerald-600' : line.type === 'deletion' ? 'text-red-600' : 'text-muted-foreground'}>{line.type === 'addition' ? '+' : line.type === 'deletion' ? '-' : ' '} {line.content}</div>)}</div> : <div className="text-[8px] text-muted-foreground">No diff available.</div>}</aside>
}
